FROM python:3.11

RUN mkdir /django_app

WORKDIR /django_app

COPY requirements.txt .

RUN pip install --upgrade pip
RUN pip install -r requirements.txt


env DB_HOST=dpg-cm9fipn109ks73cjajk0-a
env DB_PORT=5432
env DB_NAME=vlad
env DB_USER=vlad
env DB_PASS=Fveamc0HjomZGodM9WdH3nI63fHycClX
env PYTHONDONTWRITEBYTECODE=1
env PYTHONUNBUFFERED=1

COPY . .