FROM python:3.11

RUN mkdir /django_app

WORKDIR /django_app

COPY requirements.txt .

ENV DB_HOST=dpg-cm9fipn109ks73cjajk0-a
ENV DB_PORT=5432
ENV DB_NAME=vlad
ENV DB_USER=vlad
ENV DB_PASS=Fveamc0HjomZGodM9WdH3nI63fHycClX
ENV PIP_ROOT_USER_ACTION=ignore
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

CMD python manage.py migrate --settings=config.settings.prod && python manage.py createsuperuser --no-input --settings=config.settings.prod && gunicorn config.asgi:application --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000 --env DJANGO_SETTINGS_MODULE=config.settings.prod

COPY . .