FROM python:3.11

RUN mkdir /django_app

WORKDIR /django_app

COPY requirements.txt .


env DB_HOST=dpg-cm9fipn109ks73cjajk0-a
env DB_PORT=5432
env DB_NAME=vlad
env DB_USER=vlad
env DB_PASS=Fveamc0HjomZGodM9WdH3nI63fHycClX
env PIP_ROOT_USER_ACTION=ignore
env PYTHONDONTWRITEBYTECODE=1
env PYTHONUNBUFFERED=1

run pip install --upgrade pip
run pip install -r requirements.txt

WORKDIR /config
CMD ["python", "manage.py", "migrate", "--settings=config.settings.prod"] && ["python", "manage.py", "createsuperuser", "--no-input", "--settings=config.settings.prod"] && ["gunicorn", "config.asgi:application", "--workers", "4", "--worker-class", "uvicorn.workers.UvicornWorker", "--bind=0.0.0.0:8000", "--env", "DJANGO_SETTINGS_MODULE=config.settings.prod"]

COPY . .