version: '3.7'

services:
  db:
    image: postgres
    container_name: db
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data/

  app:
    build:
      context: .
    env_file:
      - .env
    container_name: django_app
    command: bash -c "
      cd config &&
      python manage.py migrate --settings=config.settings.prod && 
      python manage.py createsuperuser --no-input --settings=config.settings.prod && 
      gunicorn config.asgi:application --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000 --env DJANGO_SETTINGS_MODULE=config.settings.prod
      "
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  pgdata:
